default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: shorturl_devevelopment

test:
  <<: *default
  database: shorturl_test

production:
  <<: *default
  database: shorturl_production
