# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9281b07cb35702fb8e10ee556d787c6b1f263c577e9351cac5d686957a02c4366bf0584fa1cb35e65a33e7870b0c9b8e83a49a4a670255e0c6f194fe7f70482e

test:
  secret_key_base: 0047ce13f91480c0f5c5981daa3734e3be6a5653c59d6be77c0605c4628524086d2abf95b5860eb89fa79e19e075d76f2caa55278b74f76293f1757444607db0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
